// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uflozqxlbkkqaghmzsyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmbG96cXhsYmtrcWFnaG16c3l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Njg3NzksImV4cCI6MjA3MjM0NDc3OX0.0WOHzhG_g9LGSAhxI0MGGJZ0qhK-4ry-uvNGrAJo-IE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});